#!/bin/sh
# =============================================================================
# GL-X3000 (MT7981A, aarch64 LE) — verify the reworked 992 XDP hook, the kernel
# config claims, and the telegraf footprint.  Self-contained: the BPF objects
# are embedded, so nothing needs to be compiled on the box.
#
#   sh verify-992a.sh              read-only + safe attach tests
#   sh verify-992a.sh --with-drop  additionally test XDP_DROP (5s WAN blackout)
#   sh verify-992a.sh --with-tc    additionally test tc-BPF L3/L4 on raw IP
#   sh verify-992a.sh --traffic    start a WAN download so steps 4/6 have data
#   (flags combine; --traffic is what makes the GRO test meaningful)
#
# Every mutation is undone before exit, including on Ctrl-C.
# =============================================================================
PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$((PASS+1)); printf '  [ OK ]  %s\n' "$1"; }
bad()  { FAIL=$((FAIL+1)); printf '  [FAIL]  %s\n' "$1"; }
skip() { SKIP=$((SKIP+1)); printf '  [skip]  %s\n' "$1"; }
info() { printf '          %s\n' "$1"; }
hdr()  { printf '\n===== %s =====\n' "$1"; }

WANIF=${WANIF:-wwan0}
D=/tmp/verify992a; rm -rf $D; mkdir -p $D

# Capture flags NOW: gro_measure() uses `set --`, which would clobber "$@".
for a in "$@"; do
	case "$a" in
		--with-drop) WITH_DROP=1 ;;
		--with-tc)   WITH_TC=1 ;;
		--traffic)   WITH_TRAFFIC=1 ;;
		--help|-h)   sed -n '3,12p' "$0"; exit 0 ;;
		*)           echo "unknown option: $a" >&2; exit 2 ;;
	esac
done

# OpenWrt ships busybox's cut-down `ip`/`tc` as well as the real ones. Busybox
# ip cannot do `xdp`, so pick a capable binary or say so plainly.
pick() {
	for c in "$@"; do
		[ -x "$c" ] || continue
		case "$1" in *ip*) "$c" link help 2>&1 | grep -qi xdp && { echo "$c"; return; } ;;
		            *)     "$c" -V >/dev/null 2>&1 && { echo "$c"; return; } ;;
		esac
	done
	echo ""
}
IP=$(pick /usr/libexec/ip-full /sbin/ip /usr/sbin/ip /bin/ip)
TC=$(pick /usr/libexec/tc-bpf /sbin/tc /usr/sbin/tc)
if [ -z "$IP" ]; then
	echo "FATAL: no iproute2 'ip' that understands xdp." >&2
	echo "       install ip-full (CONFIG_PACKAGE_ip-full=y) and re-run." >&2
	exit 2
fi

TRAFFIC_PID=""
start_traffic() {
	[ "$WITH_TRAFFIC" = 1 ] || return
	for u in "https://speed.cloudflare.com/__down?bytes=1000000000" \
	         "http://speedtest.tele2.net/1GB.zip"; do
		if command -v wget >/dev/null 2>&1; then
			wget -q -O /dev/null "$u" 2>/dev/null &
			TRAFFIC_PID=$!
			sleep 2
			kill -0 "$TRAFFIC_PID" 2>/dev/null && { info "load generator running (pid $TRAFFIC_PID, $u)"; return; }
		fi
	done
	TRAFFIC_PID=""
	info "could not start a load generator — drive traffic yourself for steps 4 and 6"
}
stop_traffic() { [ -n "$TRAFFIC_PID" ] && kill "$TRAFFIC_PID" 2>/dev/null; TRAFFIC_PID=""; }

cleanup() {
	stop_traffic
	$IP link set dev "$WANIF" xdp off 2>/dev/null
	$IP link set dev "$WANIF" xdpgeneric off 2>/dev/null
	$TC filter del dev "$WANIF" ingress 2>/dev/null
	[ -n "$MADE_CLSACT" ] && $TC qdisc del dev "$WANIF" clsact 2>/dev/null
	rm -rf $D
}
trap 'echo; echo "interrupted — reverting"; cleanup; exit 130' INT TERM

# ---- embedded, pre-verified BPF objects (little-endian eBPF bytecode) -------
emit() { echo "$2" | base64 -d > "$D/$1" 2>/dev/null || { echo "$2" | base64 -d -i > "$D/$1"; }; }
emit xdp_pass.o 'f0VMRgIBAQAAAAAAAAAAAAEA9wABAAAAAAAAAAAAAAAAAAAAAAAAAMAJAAAAAAAAAAAAAEAAAAAAAEAAGAABALcAAAACAAAAlQAAAAAAAABHUEwAAREBJSUTBQMlchcQFxslERsSBnMXAAACNAADJUkTPxk6CzsLAhgAAAMBAUkTAAAEIQBJEzcLAAAFJAADJT4LCwsAAAYkAAMlCws+CwAABy4BERsSBkAYehkDJToLOwsnGUkTPxkAAAgFAAMlOgs7C0kTAAAJDwBJEwAAChMBAyULCzoLOwsAAAsNAAMlSRM6CzsLOAsAAACgAAAABQABCAAAAAABAB0AAQgAAAAAAAAAAgEQAAAACAAAAAIDLgAAAAAEAqEAAzoAAAAEPgAAAAQABQQGAQYFCAcHARAAAAABWgYAA1oAAAAICAADXgAAAAAFBwUECWMAAAAKEBgAAgsJnwAAAAACAAsLnwAAAAACBAsMnwAAAAACCAsNnwAAAAACDAsOnwAAAAACEAsPnwAAAAACFAAFCgcEAEgAAAAFAAAAAAAAACcAAAAyAAAARwAAAFAAAABVAAAAaQAAAHIAAAB2AAAAegAAAH8AAACMAAAAlQAAAJ8AAACvAAAAvgAAAM0AAABVYnVudHUgY2xhbmcgdmVyc2lvbiAxOC4xLjMgKDF1YnVudHUxKQB4ZHBfcGFzcy5jAC9ob21lL2NsYXVkZS94ZHB0ZXN0AF9saWNlbnNlAGNoYXIAX19BUlJBWV9TSVpFX1RZUEVfXwB4ZHBfcGFzcwBpbnQAY3R4AGRhdGEAdW5zaWduZWQgaW50AGRhdGFfZW5kAGRhdGFfbWV0YQBpbmdyZXNzX2lmaW5kZXgAcnhfcXVldWVfaW5kZXgAZWdyZXNzX2lmaW5kZXgAeGRwX21kABQAAAAFAAgAAAAAAAAAAAAAAAAAAAAAAJ/rAQAYAAAAAAAAAAABAAAAAQAA9AAAAAAAAAAAAAACAgAAAAEAAAAGAAAEGAAAAAgAAAADAAAAAAAAAA0AAAADAAAAIAAAABYAAAADAAAAQAAAACAAAAADAAAAYAAAADAAAAADAAAAgAAAAD8AAAADAAAAoAAAAE4AAAAAAAABBAAAACAAAAAAAAAAAQAADQUAAABbAAAAAQAAAF8AAAAAAAABBAAAACAAAAFjAAAAAQAADAQAAADKAAAAAAAAAQEAAAAIAAABAAAAAAAAAAMAAAAABwAAAAkAAAAEAAAAzwAAAAAAAAEEAAAAIAAAAOMAAAAAAAAOCAAAAAEAAADsAAAAAQAADwAAAAAKAAAAAAAAAAQAAAAAeGRwX21kAGRhdGEAZGF0YV9lbmQAZGF0YV9tZXRhAGluZ3Jlc3NfaWZpbmRleAByeF9xdWV1ZV9pbmRleABlZ3Jlc3NfaWZpbmRleAB1bnNpZ25lZCBpbnQAY3R4AGludAB4ZHBfcGFzcwB4ZHAAL2hvbWUvY2xhdWRlL3hkcHRlc3QveGRwX3Bhc3MuYwBTRUMoInhkcCIpIGludCB4ZHBfcGFzcyhzdHJ1Y3QgeGRwX21kICpjdHgpIHsgcmV0dXJuIDI7IH0AY2hhcgBfX0FSUkFZX1NJWkVfVFlQRV9fAF9saWNlbnNlAGxpY2Vuc2UAn+sBACAAAAAAAAAAFAAAABQAAAAcAAAAMAAAAAAAAAAIAAAAbAAAAAEAAAAAAAAABgAAABAAAABsAAAAAQAAAAAAAABwAAAAkAAAAC8MAAAAAAAADAAAAP////8EAAgACHwLABQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFUAAAAFAAgANwAAAAgBAfsODQABAQEBAAAAAQAAAQEBHwEAAAAAAwEfAg8FHgEVAAAAAG1FsXYXHktNS2pLH383nIwEAAUvCgAJAgAAAAAAAAAAFAICAAEBL2hvbWUvY2xhdWRlL3hkcHRlc3QAeGRwX3Bhc3MuYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuQAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAMACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAFQAAAAAAAAAAAAAAAAAAAAAAOQAAABIAAwAAAAAAAAAAABAAAAAAAAAAjwAAABEABAAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAADAAAAAwAAABEAAAAAAAAAAwAAAAQAAAAVAAAAAAAAAAMAAAAIAAAAHwAAAAAAAAADAAAABgAAAAgAAAAAAAAAAwAAAAUAAAAMAAAAAAAAAAMAAAAFAAAAEAAAAAAAAAADAAAABQAAABQAAAAAAAAAAwAAAAUAAAAYAAAAAAAAAAMAAAAFAAAAHAAAAAAAAAADAAAABQAAACAAAAAAAAAAAwAAAAUAAAAkAAAAAAAAAAMAAAAFAAAAKAAAAAAAAAADAAAABQAAACwAAAAAAAAAAwAAAAUAAAAwAAAAAAAAAAMAAAAFAAAANAAAAAAAAAADAAAABQAAADgAAAAAAAAAAwAAAAUAAAA8AAAAAAAAAAMAAAAFAAAAQAAAAAAAAAADAAAABQAAAEQAAAAAAAAAAwAAAAUAAABIAAAAAAAAAAMAAAAFAAAACAAAAAAAAAACAAAACwAAABAAAAAAAAAAAgAAAAIAAAAQAQAAAAAAAAQAAAALAAAALAAAAAAAAAAEAAAAAgAAAEAAAAAAAAAABAAAAAIAAAAUAAAAAAAAAAMAAAAHAAAAGAAAAAAAAAACAAAAAgAAACIAAAAAAAAAAwAAAAkAAAAuAAAAAAAAAAMAAAAJAAAASwAAAAAAAAACAAAAAgAAAAoLAC5kZWJ1Z19hYmJyZXYALnRleHQALnJlbC5CVEYuZXh0AC5yZWwuZGVidWdfc3RyX29mZnNldHMAeGRwX3Bhc3MALmRlYnVnX3N0cgAuZGVidWdfbGluZV9zdHIALnJlbC5kZWJ1Z19hZGRyAHhkcAAucmVsLmRlYnVnX2luZm8ALmxsdm1fYWRkcnNpZwBfbGljZW5zZQAucmVsLmRlYnVnX2xpbmUALnJlbC5kZWJ1Z19mcmFtZQB4ZHBfcGFzcy5jAC5zdHJ0YWIALnN5bXRhYgAucmVsLkJURgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAADAAAAAAAAAAAAAAAAAAAAAAAAAOIIAAAAAAAA3QAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAPAAAAAQAAAAYAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAbQAAAAEAAAAGAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAJAAAAABAAAAAwAAAAAAAAAAAAAAAAAAAFAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAAJgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAdQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA7AAAAAAAAACkAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHEAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAPAGAAAAAAAAQAAAAAAAAAAXAAAABgAAAAgAAAAAAAAAEAAAAAAAAAAmAAAAAQAAAAAAAAAAAAAAAAAAAAAAAACQAQAAAAAAAEwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIgAAAAkAAABAAAAAAAAAAAAAAAAAAAAAMAcAAAAAAAAQAQAAAAAAABcAAAAIAAAACAAAAAAAAAAQAAAAAAAAAEIAAAABAAAAMAAAAAAAAAAAAAAAAAAAANwBAAAAAAAA1AAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAABhAAAAAQAAAAAAAAAAAAAAAAAAAAAAAACwAgAAAAAAABgAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAXQAAAAkAAABAAAAAAAAAAAAAAAAAAAAAQAgAAAAAAAAgAAAAAAAAABcAAAALAAAACAAAAAAAAAAQAAAAAAAAANgAAAABAAAAAAAAAAAAAAAAAAAAAAAAAMgCAAAAAAAADAIAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADUAAAACQAAAEAAAAAAAAAAAAAAAAAAAABgCAAAAAAAABAAAAAAAAAAFwAAAA0AAAAIAAAAAAAAABAAAAAAAAAAGQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA1AQAAAAAAABQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABUAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAHAIAAAAAAAAIAAAAAAAAAAXAAAADwAAAAgAAAAAAAAAEAAAAAAAAACsAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAoBQAAAAAAACgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAqAAAAAkAAABAAAAAAAAAAAAAAAAAAAAAkAgAAAAAAAAgAAAAAAAAABcAAAARAAAACAAAAAAAAAAQAAAAAAAAAJwAAAABAAAAAAAAAAAAAAAAAAAAAAAAAFAFAAAAAAAAWQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACYAAAACQAAAEAAAAAAAAAAAAAAAAAAAACwCAAAAAAAADAAAAAAAAAAFwAAABMAAAAIAAAAAAAAABAAAAAAAAAATQAAAAEAAAAwAAAAAAAAAAAAAAAAAAAAqQUAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAIEAAAADTP9vAAAAgAAAAAAAAAAAAAAAAOAIAAAAAAAAAgAAAAAAAAAXAAAAAAAAAAEAAAAAAAAAAAAAAAAAAADMAAAAAgAAAAAAAAAAAAAAAAAAAAAAAADQBQAAAAAAACABAAAAAAAAAQAAAAoAAAAIAAAAAAAAABgAAAAAAAAA'
emit xdp_drop.o 'f0VMRgIBAQAAAAAAAAAAAAEA9wABAAAAAAAAAAAAAAAAAAAAAAAAANAJAAAAAAAAAAAAAEAAAAAAAEAAGAABALcAAAABAAAAlQAAAAAAAABHUEwAAREBJSUTBQMlchcQFxslERsSBnMXAAACNAADJUkTPxk6CzsLAhgAAAMBAUkTAAAEIQBJEzcLAAAFJAADJT4LCwsAAAYkAAMlCws+CwAABy4BERsSBkAYehkDJToLOwsnGUkTPxkAAAgFAAMlOgs7C0kTAAAJDwBJEwAAChMBAyULCzoLOwsAAAsNAAMlSRM6CzsLOAsAAACgAAAABQABCAAAAAABAB0AAQgAAAAAAAAAAgEQAAAACAAAAAIDLgAAAAAEAqEAAzoAAAAEPgAAAAQABQQGAQYFCAcHARAAAAABWgYAA1oAAAAICAADXgAAAAAFBwUECWMAAAAKEBgAAgsJnwAAAAACAAsLnwAAAAACBAsMnwAAAAACCAsNnwAAAAACDAsOnwAAAAACEAsPnwAAAAACFAAFCgcEAEgAAAAFAAAAAAAAACcAAAAyAAAARwAAAFAAAABVAAAAaQAAAHIAAAB2AAAAegAAAH8AAACMAAAAlQAAAJ8AAACvAAAAvgAAAM0AAABVYnVudHUgY2xhbmcgdmVyc2lvbiAxOC4xLjMgKDF1YnVudHUxKQB4ZHBfZHJvcC5jAC9ob21lL2NsYXVkZS94ZHB0ZXN0AF9saWNlbnNlAGNoYXIAX19BUlJBWV9TSVpFX1RZUEVfXwB4ZHBfZHJvcABpbnQAY3R4AGRhdGEAdW5zaWduZWQgaW50AGRhdGFfZW5kAGRhdGFfbWV0YQBpbmdyZXNzX2lmaW5kZXgAcnhfcXVldWVfaW5kZXgAZWdyZXNzX2lmaW5kZXgAeGRwX21kABQAAAAFAAgAAAAAAAAAAAAAAAAAAAAAAJ/rAQAYAAAAAAAAAAABAAAAAQAABQEAAAAAAAAAAAACAgAAAAEAAAAGAAAEGAAAAAgAAAADAAAAAAAAAA0AAAADAAAAIAAAABYAAAADAAAAQAAAACAAAAADAAAAYAAAADAAAAADAAAAgAAAAD8AAAADAAAAoAAAAE4AAAAAAAABBAAAACAAAAAAAAAAAQAADQUAAABbAAAAAQAAAF8AAAAAAAABBAAAACAAAAFjAAAAAQAADAQAAADbAAAAAAAAAQEAAAAIAAABAAAAAAAAAAMAAAAABwAAAAkAAAAEAAAA4AAAAAAAAAEEAAAAIAAAAPQAAAAAAAAOCAAAAAEAAAD9AAAAAQAADwAAAAAKAAAAAAAAAAQAAAAAeGRwX21kAGRhdGEAZGF0YV9lbmQAZGF0YV9tZXRhAGluZ3Jlc3NfaWZpbmRleAByeF9xdWV1ZV9pbmRleABlZ3Jlc3NfaWZpbmRleAB1bnNpZ25lZCBpbnQAY3R4AGludAB4ZHBfZHJvcAB4ZHAAL2hvbWUvY2xhdWRlL3hkcHRlc3QveGRwX2Ryb3AuYwBTRUMoInhkcCIpIGludCB4ZHBfZHJvcChzdHJ1Y3QgeGRwX21kICpjdHgpIHsgcmV0dXJuIDE7IH0gICAvKiBYRFBfRFJPUCAqLwBjaGFyAF9fQVJSQVlfU0laRV9UWVBFX18AX2xpY2Vuc2UAbGljZW5zZQAAAACf6wEAIAAAAAAAAAAUAAAAFAAAABwAAAAwAAAAAAAAAAgAAABsAAAAAQAAAAAAAAAGAAAAEAAAAGwAAAABAAAAAAAAAHAAAACQAAAALwwAAAwAAAD/////BAAIAAh8CwAUAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABVAAAABQAIADcAAAAIAQH7Dg0AAQEBAQAAAAEAAAEBAR8BAAAAAAMBHwIPBR4BFQAAAADg4I8LYMjWhg5nB6RBR3YHBAAFLwoACQIAAAAAAAAAABQCAgABAS9ob21lL2NsYXVkZS94ZHB0ZXN0AHhkcF9kcm9wLmMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALkAAAAEAPH/AAAAAAAAAAAAAAAAAAAAAAAAAAADAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAADABEAAAAAAAAAAAAAAAAAAAAAAAAAAAADABMAAAAAAAAAAAAAAAAAAAAAAAAAAAADABUAAAAAAAAAAAAAAAAAAAAAAGQAAAASAAMAAAAAAAAAAAAQAAAAAAAAAI8AAAARAAQAAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAwAAAAMAAAARAAAAAAAAAAMAAAAEAAAAFQAAAAAAAAADAAAACAAAAB8AAAAAAAAAAwAAAAYAAAAIAAAAAAAAAAMAAAAFAAAADAAAAAAAAAADAAAABQAAABAAAAAAAAAAAwAAAAUAAAAUAAAAAAAAAAMAAAAFAAAAGAAAAAAAAAADAAAABQAAABwAAAAAAAAAAwAAAAUAAAAgAAAAAAAAAAMAAAAFAAAAJAAAAAAAAAADAAAABQAAACgAAAAAAAAAAwAAAAUAAAAsAAAAAAAAAAMAAAAFAAAAMAAAAAAAAAADAAAABQAAADQAAAAAAAAAAwAAAAUAAAA4AAAAAAAAAAMAAAAFAAAAPAAAAAAAAAADAAAABQAAAEAAAAAAAAAAAwAAAAUAAABEAAAAAAAAAAMAAAAFAAAASAAAAAAAAAADAAAABQAAAAgAAAAAAAAAAgAAAAsAAAAQAAAAAAAAAAIAAAACAAAAEAEAAAAAAAAEAAAACwAAACwAAAAAAAAABAAAAAIAAABAAAAAAAAAAAQAAAACAAAAFAAAAAAAAAADAAAABwAAABgAAAAAAAAAAgAAAAIAAAAiAAAAAAAAAAMAAAAJAAAALgAAAAAAAAADAAAACQAAAEsAAAAAAAAAAgAAAAIAAAAKCwAuZGVidWdfYWJicmV2AC50ZXh0AC5yZWwuQlRGLmV4dAAucmVsLmRlYnVnX3N0cl9vZmZzZXRzAC5kZWJ1Z19zdHIALmRlYnVnX2xpbmVfc3RyAC5yZWwuZGVidWdfYWRkcgB4ZHBfZHJvcAB4ZHAALnJlbC5kZWJ1Z19pbmZvAC5sbHZtX2FkZHJzaWcAX2xpY2Vuc2UALnJlbC5kZWJ1Z19saW5lAC5yZWwuZGVidWdfZnJhbWUAeGRwX2Ryb3AuYwAuc3RydGFiAC5zeW10YWIALnJlbC5CVEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADyCAAAAAAAAN0AAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAADwAAAAEAAAAGAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAG0AAAABAAAABgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAACQAAAAAQAAAAMAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAVAAAAAAAAACYAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHUAAAABAAAAAAAAAAAAAAAAAAAAAAAAAOwAAAAAAAAApAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABxAAAACQAAAEAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAEAAAAAAAAAAFwAAAAYAAAAIAAAAAAAAABAAAAAAAAAAJgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAkAEAAAAAAABMAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAACIAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAEAHAAAAAAAAEAEAAAAAAAAXAAAACAAAAAgAAAAAAAAAEAAAAAAAAAA5AAAAAQAAADAAAAAAAAAAAAAAAAAAAADcAQAAAAAAANQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAWAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAsAIAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAFQAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAFAIAAAAAAAAIAAAAAAAAAAXAAAACwAAAAgAAAAAAAAAEAAAAAAAAADYAAAAAQAAAAAAAAAAAAAAAAAAAAAAAADIAgAAAAAAAB0CAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA1AAAAAkAAABAAAAAAAAAAAAAAAAAAAAAcAgAAAAAAAAQAAAAAAAAABcAAAANAAAACAAAAAAAAAAQAAAAAAAAABkAAAABAAAAAAAAAAAAAAAAAAAAAAAAAOgEAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAVAAAACQAAAEAAAAAAAAAAAAAAAAAAAACACAAAAAAAACAAAAAAAAAAFwAAAA8AAAAIAAAAAAAAABAAAAAAAAAArAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAOAUAAAAAAAAoAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAKgAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAKAIAAAAAAAAIAAAAAAAAAAXAAAAEQAAAAgAAAAAAAAAEAAAAAAAAACcAAAAAQAAAAAAAAAAAAAAAAAAAAAAAABgBQAAAAAAAFkAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAmAAAAAkAAABAAAAAAAAAAAAAAAAAAAAAwAgAAAAAAAAwAAAAAAAAABcAAAATAAAACAAAAAAAAAAQAAAAAAAAAEQAAAABAAAAMAAAAAAAAAAAAAAAAAAAALkFAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAACBAAAAA0z/bwAAAIAAAAAAAAAAAAAAAADwCAAAAAAAAAIAAAAAAAAAFwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAzAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAA4AUAAAAAAAAgAQAAAAAAAAEAAAAKAAAACAAAAAAAAAAYAAAAAAAAAA=='
emit tc_rawip.o 'f0VMRgIBAQAAAAAAAAAAAAEA9wABAAAAAAAAAAAAAAAAAAAAAAAAACAjAAAAAAAAAAAAAEAAAAAAAEAAGwABAGETUAAAAAAAYRJMAAAAAAC/JAAAAAAAAAcEAAAUAAAALTSLAAAAAABxIwAAAAAAAL80AAAAAAAAdwQAAAQAAAAVBGMABgAAAFUEdgAEAAAAexrI/wAAAABxIQwAAAAAAGcBAAAYAAAAcScNAAAAAABnBwAAEAAAAE8XAAAAAAAAcSEQAAAAAABnAQAAGAAAAHEoEQAAAAAAZwgAABAAAABPGAAAAAAAAHEhEgAAAAAAZwEAAAgAAABPGAAAAAAAAHEhEwAAAAAATxgAAAAAAABxIQ4AAAAAAGcBAAAIAAAATxcAAAAAAABxIQ8AAAAAAE8XAAAAAAAAtwUAAAAAAABxJAkAAAAAAGcDAAACAAAAVwMAADwAAAC3AQAAFAAAALcJAAAAAAAAtwYAAAAAAAAtMRQAAAAAAL9GAAAAAAAAv6QAAAAAAAAHBAAA/P///3mhyP8AAAAAvzIAAAAAAAC/QwAAAAAAALcEAAAEAAAAhQAAABoAAAC3BQAAAAAAAL9kAAAAAAAAtwYAAAAAAABVAAgAAAAAAHGp/v8AAAAAZwkAAAgAAABxof//AAAAAE8ZAAAAAAAAcab8/wAAAABnBgAACAAAAHGh/f8AAAAATxYAAAAAAABzWvL/AAAAALcBAAAleAAAaxrw/wAAAAAYAQAAPSV4IAAAAABkc3Q9exro/wAAAAAYAQAAbz0lZAAAAAAgc3Jjexrg/wAAAAAYAQAAIHY0IAAAAABwcm90exrY/wAAAAAYAQAAUkFXSQAAAABQLU9LexrQ/wAAAAC/oQAAAAAAAAcBAADQ////twIAACMAAAC/QwAAAAAAAL90AAAAAAAAv4UAAAAAAACFAAAABgAAALcBAAB4AAAAaxr4/wAAAAAYAQAAYnBybwAAAAB0bz0lexrw/wAAAAAYAQAAcnQ9JQAAAABkIHNrexro/wAAAAAYAQAAdD0lZAAAAAAgZHBvexrg/wAAAAAYAQAAIEw0IAAAAABzcG9yexrY/wAAAAAYAQAAUkFXSQAAAABQLU9LexrQ/wAAAAB5ocj/AAAAAGEVEAAAAAAA3AUAABAAAAC/oQAAAAAAAAcBAADQ////twIAACoAAAC/YwAAAAAAAL+UAAAAAAAAhQAAAAYAAAAFACQAAAAAALcDAABkAAAAazrs/wAAAAC3AwAAZW49JWM66P8AAAAAGAMAAGhkcj0AAAAAJWQgbHs64P8AAAAAGAMAACB2NiAAAAAAbmV4dHs62P8AAAAAGAMAAFJBV0kAAAAAUC1PS3s60P8AAAAAYRQAAAAAAABxIwYAAAAAAL+hAAAAAAAABwEAAND///+3AgAAHgAAAIUAAAAGAAAABQAQAAAAAAC3AQAAAAAAAHMa6P8AAAAAGAEAAGliYmwAAAAAZT0lZHsa4P8AAAAAGAEAACBmaXIAAAAAc3Rfbnsa2P8AAAAAGAEAAFJBV0kAAAAAUC0/P3sa0P8AAAAAdwMAAAQAAAC/oQAAAAAAAAcBAADQ////twIAABkAAACFAAAABgAAALcAAAAAAAAAlQAAAAAAAABSQVdJUC1PSyB2NCBwcm90bz0lZCBzcmM9JXggZHN0PSV4AFJBV0lQLU9LIEw0IHNwb3J0PSVkIGRwb3J0PSVkIHNrYnByb3RvPSV4AFJBV0lQLU9LIHY2IG5leHRoZHI9JWQgbGVuPSVkAFJBV0lQLT8/IGZpcnN0X25pYmJsZT0lZABHUEwAjwAAAAUACAAIAAAAIAAAADQAAABJAAAATwAAAFcAAABfAAAAZwAAAHcAAAAEAGABUQTgBuAHAVEEgAiICAFRAAQQ4AIBUgTgBvAHAVIEgAj4CAFSAAQQMAFTAATQAeAGAVgABPgB4AYBVwAEmALoAgFTAASgArgDAjCfBLgD4AYBWQAEoAKYAwIwnwTYA+AGAVYAAREBJSUTBQMlchcQFxslERsSBnMXdBeMARcAAAI0AAMlSRM/GToLOwsCGAAAAwEBSRMAAAQhAEkTNwsAAAUkAAMlPgsLCwAABiQAAyULCz4LAAAHNAADJUkTOgs7CxwPAAAIDwBJEwAACRUBSRMnGQAACgUASRMAAAsmAAAADBYASRMDJToLOwsAAA0PAAAADhgAAAAPJgBJEwAAEC4BERsSBkAYehkDJToLOwsnGUkTPxkAABEFAAIiAyU6CzsLSRMAABI0AAIYAyU6CzsLSRMAABM0AAIiAyU6CzsLSRMAABQ0AAMlOgs7C0kTAAAVCwERGxIGAAAWCwFVIwAAFxMBAyULCzoLOwsAABgNAAMlSRM6CzsLOAsAAADTAgAABQABCAAAAAABAB0AAQgAAAAAAAAAAgGQBAAACAAAAAwAAAAMAAAAAgM2AAAAACgCoQADQgAAAARGAAAABAAFBAYBBgUIBwcGUwAAAAEYGghYAAAACXIAAAAKdgAAAAp8AAAACogAAAAKfAAAAAAFBwUICHsAAAALDIQAAAAJAQQFCAcEDQcKkgAAAAESBgiXAAAACXIAAAAKqAAAAAp8AAAADgAIrQAAAA9CAAAACLcAAAAMvwAAAAwBAgULCAEMywAAAA4BAwUNBwIQAZAEAAABWg8ACIkBAAARABMACMkBAAASApE0EQANjQEAABMBLwAMsgAAABMCMAALiAAAABQjAAqIAAAAFQIIAwAAEwMxABZ8AAAAEwQyABV8AAAAEwUzABN8AAAAEwY0ABfDAAAAEwc1ABfDAAAAFDYAFLcAAAAWABICkQgSAB6ZAQAAABYBEgKRCBIAH6UBAAAAABUDmAAAABICkQgSACKxAQAAABUEeAAAABICkQgSACS9AQAAAAAFEAUEA7cAAAAERgAAAAQAA0IAAAAERgAAACMAA0IAAAAERgAAACoAA0IAAAAERgAAAB4AA0IAAAAERgAAABkACM4BAAAXLpABBxgUfAAAAAEIABgVfAAAAAEIBBgWfAAAAAEICBgXfAAAAAEIDBgYfAAAAAEIEBgZfAAAAAEIFBgafAAAAAEJGBgbfAAAAAEJHBgcfAAAAAEJIBgdfAAAAAEJJBgefAAAAAEJKBgffAAAAAEKLBggvgIAAAEKMBghfAAAAAEKRBgifAAAAAEKSBgjfAAAAAEKTBgkfAAAAAEKUBglfAAAAAEKVBgmfAAAAAELWBgnfAAAAAELXBgofAAAAAELYBgpygIAAAELZBgqygIAAAELdBgrfAAAAAEMhBgsfAAAAAEMiBgtfAAAAAEMjAADfAAAAARGAAAABQADfAAAAARGAAAABAAAJgAAAAUACAACAAAACAAAABMAAAAE2APYBATgBJAFAASQBbAGBLgG4AYA4AAAAAUAAAAAAAAAJwAAADIAAABGAAAATwAAAFQAAABoAAAAewAAAIAAAACNAAAAkwAAAKQAAACyAAAAtwAAAMYAAADMAAAA0gAAANYAAADcAAAA5AAAAOgAAADsAAAA9QAAAPoAAAAIAQAAEQEAAB4BAAAnAQAAMgEAADsBAABLAQAAUwEAAFwBAABfAQAAZAEAAG8BAAB0AQAAfQEAAIUBAACMAQAAlwEAAKEBAACsAQAAtgEAAMIBAADNAQAA1wEAAOEBAADkAQAA6AEAAO4BAAD0AQAA+AEAAP4BAAAEAgAAVWJ1bnR1IGNsYW5nIHZlcnNpb24gMTguMS4zICgxdWJ1bnR1MSkAdGNfcmF3aXAuYwAvaG9tZS9jbGF1ZGUvdGN0ZXN0AF9saWNlbnNlAGNoYXIAX19BUlJBWV9TSVpFX1RZUEVfXwBicGZfc2tiX2xvYWRfYnl0ZXMAbG9uZwB1bnNpZ25lZCBpbnQAX191MzIAYnBmX3RyYWNlX3ByaW50awB1bnNpZ25lZCBjaGFyAF9fdTgAdW5zaWduZWQgc2hvcnQAX191MTYAcmF3aXAAaW50AHBvcnRzAF9fX19mbXQAc2tiAGxlbgBwa3RfdHlwZQBtYXJrAHF1ZXVlX21hcHBpbmcAcHJvdG9jb2wAdmxhbl9wcmVzZW50AHZsYW5fdGNpAHZsYW5fcHJvdG8AcHJpb3JpdHkAaW5ncmVzc19pZmluZGV4AGlmaW5kZXgAdGNfaW5kZXgAY2IAaGFzaAB0Y19jbGFzc2lkAGRhdGEAZGF0YV9lbmQAbmFwaV9pZABmYW1pbHkAcmVtb3RlX2lwNABsb2NhbF9pcDQAcmVtb3RlX2lwNgBsb2NhbF9pcDYAcmVtb3RlX3BvcnQAbG9jYWxfcG9ydABkYXRhX21ldGEAX19za19idWZmAGlwAGVuZABkYWRkcgBzYWRkcgBpaGwAZHBvcnQAc3BvcnQAcHJvdG8ALAAAAAUACAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAABoAwAAAAAAAAgEAAAAAAAAAACf6wEAGAAAAAAAAAAsAgAALAIAAEIEAAAAAAAAAAAAAgIAAAABAAAAGgAABJAAAAALAAAAAwAAAAAAAAAPAAAAAwAAACAAAAAYAAAAAwAAAEAAAAAdAAAAAwAAAGAAAAArAAAAAwAAAIAAAAA0AAAAAwAAAKAAAABBAAAAAwAAAMAAAABKAAAAAwAAAOAAAABVAAAAAwAAAAABAABeAAAAAwAAACABAABuAAAAAwAAAEABAAB2AAAAAwAAAGABAAB/AAAABQAAAIABAACCAAAAAwAAACACAACHAAAAAwAAAEACAACSAAAAAwAAAGACAACXAAAAAwAAAIACAACgAAAAAwAAAKACAACoAAAAAwAAAMACAACvAAAAAwAAAOACAAC6AAAAAwAAAAADAADEAAAABwAAACADAADPAAAABwAAAKADAADZAAAAAwAAACAEAADlAAAAAwAAAEAEAADwAAAAAwAAAGAEAAD6AAAAAAAACAQAAAAAAQAAAAAAAQQAAAAgAAAAAAAAAAAAAAMAAAAAAwAAAAYAAAAFAAAADQEAAAAAAAEEAAAAIAAAAAAAAAAAAAADAAAAAAMAAAAGAAAABAAAAAAAAAABAAANCQAAACEBAAABAAAAJQEAAAAAAAEEAAAAIAAAASkBAAABAAAMCAAAACwEAAAAAAABAQAAAAgAAAEAAAAAAAAAAwAAAAALAAAABgAAAAQAAAAxBAAAAAAADgwAAAABAAAAOgQAAAEAAA8AAAAADQAAAAAAAAAEAAAAAF9fc2tfYnVmZgBsZW4AcGt0X3R5cGUAbWFyawBxdWV1ZV9tYXBwaW5nAHByb3RvY29sAHZsYW5fcHJlc2VudAB2bGFuX3RjaQB2bGFuX3Byb3RvAHByaW9yaXR5AGluZ3Jlc3NfaWZpbmRleABpZmluZGV4AHRjX2luZGV4AGNiAGhhc2gAdGNfY2xhc3NpZABkYXRhAGRhdGFfZW5kAG5hcGlfaWQAZmFtaWx5AHJlbW90ZV9pcDQAbG9jYWxfaXA0AHJlbW90ZV9pcDYAbG9jYWxfaXA2AHJlbW90ZV9wb3J0AGxvY2FsX3BvcnQAZGF0YV9tZXRhAF9fdTMyAHVuc2lnbmVkIGludABfX0FSUkFZX1NJWkVfVFlQRV9fAHNrYgBpbnQAcmF3aXAAY2xhc3NpZmllci9yYXdpcAAvaG9tZS9jbGF1ZGUvdGN0ZXN0L3RjX3Jhd2lwLmMACXZvaWQgKmVuZCAgPSAodm9pZCAqKShsb25nKXNrYi0+ZGF0YV9lbmQ7AAl2b2lkICpkYXRhID0gKHZvaWQgKikobG9uZylza2ItPmRhdGE7AAlpZiAoaXAgKyAyMCA+IChfX3U4ICopZW5kKQAJaWYgKChpcFswXSA+PiA0KSA9PSA0KSB7AAkJX191MzIgc2FkZHIgPSAoaXBbMTJdPDwyNCl8KGlwWzEzXTw8MTYpfChpcFsxNF08PDgpfGlwWzE1XTsACQlfX3UzMiBkYWRkciA9IChpcFsxNl08PDI0KXwoaXBbMTddPDwxNil8KGlwWzE4XTw8OCl8aXBbMTldOwAJCV9fdTggcHJvdG8gPSBpcFs5XTsACQlfX3UzMiBpaGwgPSAoaXBbMF0gJiAweDBmKSAqIDQ7AAkJaWYgKGlobCA+PSAyMCAmJgAJCSAgICBicGZfc2tiX2xvYWRfYnl0ZXMoc2tiLCBpaGwsIHBvcnRzLCA0KSA9PSAwKSB7AAkJCWRwb3J0ID0gKHBvcnRzWzJdIDw8IDgpIHwgcG9ydHNbM107AAkJCXNwb3J0ID0gKHBvcnRzWzBdIDw8IDgpIHwgcG9ydHNbMV07AAkJYnBmX3ByaW50aygiUkFXSVAtT0sgdjQgcHJvdG89JWQgc3JjPSV4IGRzdD0leCIsIHByb3RvLCBzYWRkciwgZGFkZHIpOwAJCWJwZl9wcmludGsoIlJBV0lQLU9LIEw0IHNwb3J0PSVkIGRwb3J0PSVkIHNrYnByb3RvPSV4IiwACQlicGZfcHJpbnRrKCJSQVdJUC1PSyB2NiBuZXh0aGRyPSVkIGxlbj0lZCIsIGlwWzZdLCBza2ItPmxlbik7AAkJYnBmX3ByaW50aygiUkFXSVAtPz8gZmlyc3RfbmliYmxlPSVkIiwgaXBbMF0gPj4gNCk7AH0AY2hhcgBfbGljZW5zZQBsaWNlbnNlAAAAn+sBACAAAAAAAAAAFAAAABQAAAAMAwAAIAMAAAAAAAAIAAAALwEAAAEAAAAAAAAACgAAABAAAAAvAQAAMAAAAAAAAABAAQAAXwEAACIsAAAIAAAAQAEAAIoBAAAiKAAAEAAAAEABAACxAQAACTwAACAAAABAAQAAsQEAAAY8AAAoAAAAQAEAAM0BAAAHSAAAQAAAAEABAADNAQAABkgAAFgAAABAAQAA5wEAABJUAABgAAAAQAEAAOcBAAAYVAAAaAAAAEABAADnAQAAH1QAAHAAAABAAQAA5wEAACVUAAB4AAAAQAEAAOcBAAAdVAAAgAAAAEABAAAlAgAAElgAAIgAAABAAQAAJQIAABhYAACQAAAAQAEAACUCAAAfWAAAmAAAAEABAAAlAgAAJVgAAKAAAABAAQAAJQIAAB1YAACoAAAAQAEAACUCAAAsWAAAsAAAAEABAAAlAgAAMlgAALgAAABAAQAAJQIAACpYAADAAAAAQAEAACUCAAA3WAAAyAAAAEABAAAlAgAANlgAANAAAABAAQAA5wEAACxUAADYAAAAQAEAAOcBAAAyVAAA4AAAAEABAADnAQAAKlQAAOgAAABAAQAA5wEAADdUAADwAAAAQAEAAOcBAAA2VAAAAAEAAEABAABjAgAAEFAAAAgBAABAAQAAeQIAAB5MAAAwAQAAQAEAAJsCAAARZAAASAEAAEABAACuAgAAB2gAAJABAABAAQAAmwIAAAdkAACYAQAAQAEAAOMCAAANcAAAoAEAAEABAADjAgAAFnAAAKgBAABAAQAA4wIAAB5wAACwAQAAQAEAAOMCAAAccAAAuAEAAEABAAAKAwAADWwAAMABAABAAQAACgMAABZsAADIAQAAQAEAAAoDAAAebAAA0AEAAEABAAAKAwAAHGwAANgBAABAAQAAMQMAAAN4AABYAgAAQAEAAAAAAAAAAAAAYAIAAEABAAAxAwAAA3gAAJACAABAAQAAegMAAAN8AAAwAwAAQAEAAAAAAAAAAAAAOAMAAEABAAB6AwAAA3wAAGgDAABAAQAAtAMAAAOIAAAIBAAAQAEAAPQDAAADkAAAgAQAAEABAAAqBAAAAZwAAAwAAAD/////BAAIAAh8CwAUAAAAAAAAAAAAAAAAAAAAkAQAAAAAAABEAQAABQAIAFAAAAAIAQH7Dg0AAQEBAQAAAAEAAAEBAR8CAAAAABQAAAADAR8CDwUeAhYAAAAA8P4GDlnNTXYxjAD9iNycFSEAAAABYbAn6TEp7F/jauYCPdkvjwQABSIKAAkCAAAAAAAAAAADCgEfBQklBQYGLgUHBiMGA24gBQYDEi4Dbi4FEgYDFSAFGAYgBR8gBSUgBR0gBRIGIQUYBiAFHyAFJSAFHSAFLCAFMiAFKiAFNyAFNiAFLAYfBTIGIAUqIAU3IAU2IANrIAUQBgMUIAUeHwYDbS4FEQYDGTwGA2cgBQcGAxouBgNmZgYDGTwFDSMFFgYgBR4gBRwgBQ0GHwUWBiAFHiAFHCAFAwYjBQAGA2LyBQMDHiADYlgGAx8gBQAGA2EIPAUDAx8gA2FKBgMiLgYDXgggBgMkLgUB5wICAAEBL2hvbWUvY2xhdWRlL3RjdGVzdAAuAHRjX3Jhd2lwLmMAdGNfY29tbW9uLmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3QAAAAQA8f8AAAAAAAAAAAAAAAAAAAAAAAAAAAMAAwAAAAAAAAAAAAAAAAAAAAAAAQEAAAAAAwCABAAAAAAAAAAAAAAAAAAADwEAAAAAAwBgAwAAAAAAAAAAAAAAAAAACAEAAAAAAwAABAAAAAAAAAAAAAAAAAAAFgEAAAAAAwDYAQAAAAAAAAAAAAAAAAAAAAAAAAMABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAMADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAGAAAAAAAAAAAAAAAAAAAAAAAjwAAABIAAwAAAAAAAAAAAJAEAAAAAAAAswAAABEABQAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAADAAAACAAAABEAAAAAAAAAAwAAAAoAAAAVAAAAAAAAAAMAAAAOAAAAHwAAAAAAAAADAAAADAAAACMAAAAAAAAAAwAAAAkAAAAnAAAAAAAAAAMAAAAHAAAACAAAAAAAAAADAAAACwAAAAwAAAAAAAAAAwAAAAsAAAAQAAAAAAAAAAMAAAALAAAAFAAAAAAAAAADAAAACwAAABgAAAAAAAAAAwAAAAsAAAAcAAAAAAAAAAMAAAALAAAAIAAAAAAAAAADAAAACwAAACQAAAAAAAAAAwAAAAsAAAAoAAAAAAAAAAMAAAALAAAALAAAAAAAAAADAAAACwAAADAAAAAAAAAAAwAAAAsAAAA0AAAAAAAAAAMAAAALAAAAOAAAAAAAAAADAAAACwAAADwAAAAAAAAAAwAAAAsAAABAAAAAAAAAAAMAAAALAAAARAAAAAAAAAADAAAACwAAAEgAAAAAAAAAAwAAAAsAAABMAAAAAAAAAAMAAAALAAAAUAAAAAAAAAADAAAACwAAAFQAAAAAAAAAAwAAAAsAAABYAAAAAAAAAAMAAAALAAAAXAAAAAAAAAADAAAACwAAAGAAAAAAAAAAAwAAAAsAAABkAAAAAAAAAAMAAAALAAAAaAAAAAAAAAADAAAACwAAAGwAAAAAAAAAAwAAAAsAAABwAAAAAAAAAAMAAAALAAAAdAAAAAAAAAADAAAACwAAAHgAAAAAAAAAAwAAAAsAAAB8AAAAAAAAAAMAAAALAAAAgAAAAAAAAAADAAAACwAAAIQAAAAAAAAAAwAAAAsAAACIAAAAAAAAAAMAAAALAAAAjAAAAAAAAAADAAAACwAAAJAAAAAAAAAAAwAAAAsAAACUAAAAAAAAAAMAAAALAAAAmAAAAAAAAAADAAAACwAAAJwAAAAAAAAAAwAAAAsAAACgAAAAAAAAAAMAAAALAAAApAAAAAAAAAADAAAACwAAAKgAAAAAAAAAAwAAAAsAAACsAAAAAAAAAAMAAAALAAAAsAAAAAAAAAADAAAACwAAALQAAAAAAAAAAwAAAAsAAAC4AAAAAAAAAAMAAAALAAAAvAAAAAAAAAADAAAACwAAAMAAAAAAAAAAAwAAAAsAAADEAAAAAAAAAAMAAAALAAAAyAAAAAAAAAADAAAACwAAAMwAAAAAAAAAAwAAAAsAAADQAAAAAAAAAAMAAAALAAAA1AAAAAAAAAADAAAACwAAANgAAAAAAAAAAwAAAAsAAADcAAAAAAAAAAMAAAALAAAA4AAAAAAAAAADAAAACwAAAAgAAAAAAAAAAgAAABEAAAAQAAAAAAAAAAIAAAACAAAAGAAAAAAAAAACAAAAAgAAACAAAAAAAAAAAgAAAAIAAAAoAAAAAAAAAAIAAAACAAAAPAIAAAAAAAAEAAAAEQAAACwAAAAAAAAABAAAAAIAAABAAAAAAAAAAAQAAAACAAAAUAAAAAAAAAAEAAAAAgAAAGAAAAAAAAAABAAAAAIAAABwAAAAAAAAAAQAAAACAAAAgAAAAAAAAAAEAAAAAgAAAJAAAAAAAAAABAAAAAIAAACgAAAAAAAAAAQAAAACAAAAsAAAAAAAAAAEAAAAAgAAAMAAAAAAAAAABAAAAAIAAADQAAAAAAAAAAQAAAACAAAA4AAAAAAAAAAEAAAAAgAAAPAAAAAAAAAABAAAAAIAAAAAAQAAAAAAAAQAAAACAAAAEAEAAAAAAAAEAAAAAgAAACABAAAAAAAABAAAAAIAAAAwAQAAAAAAAAQAAAACAAAAQAEAAAAAAAAEAAAAAgAAAFABAAAAAAAABAAAAAIAAABgAQAAAAAAAAQAAAACAAAAcAEAAAAAAAAEAAAAAgAAAIABAAAAAAAABAAAAAIAAACQAQAAAAAAAAQAAAACAAAAoAEAAAAAAAAEAAAAAgAAALABAAAAAAAABAAAAAIAAADAAQAAAAAAAAQAAAACAAAA0AEAAAAAAAAEAAAAAgAAAOABAAAAAAAABAAAAAIAAADwAQAAAAAAAAQAAAACAAAAAAIAAAAAAAAEAAAAAgAAABACAAAAAAAABAAAAAIAAAAgAgAAAAAAAAQAAAACAAAAMAIAAAAAAAAEAAAAAgAAAEACAAAAAAAABAAAAAIAAABQAgAAAAAAAAQAAAACAAAAYAIAAAAAAAAEAAAAAgAAAHACAAAAAAAABAAAAAIAAACAAgAAAAAAAAQAAAACAAAAkAIAAAAAAAAEAAAAAgAAAKACAAAAAAAABAAAAAIAAACwAgAAAAAAAAQAAAACAAAAwAIAAAAAAAAEAAAAAgAAANACAAAAAAAABAAAAAIAAADgAgAAAAAAAAQAAAACAAAA8AIAAAAAAAAEAAAAAgAAAAADAAAAAAAABAAAAAIAAAAQAwAAAAAAAAQAAAACAAAAIAMAAAAAAAAEAAAAAgAAADADAAAAAAAABAAAAAIAAAAUAAAAAAAAAAMAAAANAAAAGAAAAAAAAAACAAAAAgAAACIAAAAAAAAAAwAAAA8AAAAmAAAAAAAAAAMAAAAPAAAAMgAAAAAAAAADAAAADwAAAEcAAAAAAAAAAwAAAA8AAABkAAAAAAAAAAIAAAACAAAAEBEALmRlYnVnX2FiYnJldgAudGV4dAAucmVsLkJURi5leHQALmRlYnVnX3JuZ2xpc3RzAC5kZWJ1Z19sb2NsaXN0cwAucmVsLmRlYnVnX3N0cl9vZmZzZXRzAC5kZWJ1Z19zdHIALmRlYnVnX2xpbmVfc3RyAC5yZWwuZGVidWdfYWRkcgBjbGFzc2lmaWVyL3Jhd2lwAC5yZWwuZGVidWdfaW5mbwAubGx2bV9hZGRyc2lnAF9saWNlbnNlAC5yZWwuZGVidWdfbGluZQAucmVsLmRlYnVnX2ZyYW1lAHRjX3Jhd2lwLmMALnN0cnRhYgAuc3ltdGFiAC5yZWwuQlRGAExCQjBfOQBMQkIwXzgATEJCMF83AExCQjBfNgAucm9kYXRhLnN0cjEuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADyIQAAAAAAACwBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAADwAAAAEAAAAGAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAIQAAAABAAAABgAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAkAQAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAdAQAAAQAAADIAAAAAAAAAAAAAAAAAAADQBAAAAAAAAIQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAtAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAVAUAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAFgFAAAAAAAAkwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAADrBQAAAAAAABwBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAmQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAABwcAAAAAAADXAgAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAJUAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAEAaAAAAAAAAYAAAAAAAAAAaAAAACAAAAAgAAAAAAAAAEAAAAAAAAAAiAAAAAQAAAAAAAAAAAAAAAAAAAAAAAADeCQAAAAAAACoAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAARgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAACAoAAAAAAADkAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAEIAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAKAaAAAAAAAAcAMAAAAAAAAaAAAACwAAAAgAAAAAAAAAEAAAAAAAAABZAAAAAQAAADAAAAAAAAAAAAAAAAAAAADsCgAAAAAAAAoCAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAeAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA9gwAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAHQAAAAJAAAAQAAAAAAAAAAAAAAAAAAAABAeAAAAAAAAUAAAAAAAAAAaAAAADgAAAAgAAAAAAAAAEAAAAAAAAAD8AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAoDQAAAAAAAIYGAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA+AAAAAkAAABAAAAAAAAAAAAAAAAAAAAAYB4AAAAAAAAQAAAAAAAAABoAAAAQAAAACAAAAAAAAAAQAAAAAAAAABkAAAABAAAAAAAAAAAAAAAAAAAAAAAAALATAAAAAAAAQAMAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAVAAAACQAAAEAAAAAAAAAAAAAAAAAAAABwHgAAAAAAABADAAAAAAAAGgAAABIAAAAIAAAAAAAAABAAAAAAAAAA0AAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA8BYAAAAAAAAoAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAMwAAAAJAAAAQAAAAAAAAAAAAAAAAAAAAIAhAAAAAAAAIAAAAAAAAAAaAAAAFAAAAAgAAAAAAAAAEAAAAAAAAADAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAYFwAAAAAAAEgBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAvAAAAAkAAABAAAAAAAAAAAAAAAAAAAAAoCEAAAAAAABQAAAAAAAAABoAAAAWAAAACAAAAAAAAAAQAAAAAAAAAGQAAAABAAAAMAAAAAAAAAAAAAAAAAAAAGAYAAAAAAAALQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAClAAAAA0z/bwAAAIAAAAAAAAAAAAAAAADwIQAAAAAAAAIAAAAAAAAAGgAAAAAAAAABAAAAAAAAAAAAAAAAAAAA8AAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAkBgAAAAAAACwAQAAAAAAAAEAAAAQAAAACAAAAAAAAAAYAAAAAAAAAA=='

hdr "0. identity"
info "$(uname -srvm)"
info "board: $(cat /tmp/sysinfo/model 2>/dev/null || echo unknown)"
info "kernel build stamp: $(uname -v)   <- must match the HEAD you built from"
for f in $D/xdp_pass.o $D/xdp_drop.o $D/tc_rawip.o; do
	[ -s "$f" ] || bad "embedded object $f did not decode"
done
[ -s $D/xdp_pass.o ] && ok "embedded BPF objects decoded ($(ls -l $D/xdp_pass.o | awk '{print $5}') bytes for xdp_pass.o)"

hdr "1. kernel config as shipped"
if [ -r /proc/config.gz ]; then
	zcat /proc/config.gz > $D/kcfg
	KEYS="XDP_SOCKETS DEBUG_INFO_BTF DEBUG_INFO_BTF_MODULES NF_FLOW_TABLE
	      NF_FLOW_TABLE_INET NFT_FLOW_OFFLOAD BPF_SYSCALL BPF_JIT PAGE_POOL
	      GRO_CELLS IKCONFIG_PROC"
	case "$(uname -m)" in aarch64) KEYS="$KEYS ARM64_4K_PAGES" ;; esac
	for k in $KEYS; do
		v=$(grep -E "^(# )?CONFIG_$k( is not set|=)" $D/kcfg | head -1)
		case "$v" in
			*=y|*=m) ok "$v" ;;
			*)       bad "CONFIG_$k -> ${v:-absent from .config}" ;;
		esac
	done
else
	bad "/proc/config.gz missing — CONFIG_IKCONFIG_PROC should provide it"
fi

hdr "2. BTF, and the flowtable XDP kfunc it gates"
if [ -r /sys/kernel/btf/vmlinux ]; then
	ok "/sys/kernel/btf/vmlinux present ($(( $(stat -c%s /sys/kernel/btf/vmlinux) / 1024 )) KB)"
else
	bad "/sys/kernel/btf/vmlinux missing — CO-RE programs cannot load"
fi
modprobe nf_flow_table 2>/dev/null
if [ -r /sys/kernel/btf/nf_flow_table ]; then
	ok "module BTF for nf_flow_table present (DEBUG_INFO_BTF_MODULES working)"
	if command -v bpftool >/dev/null 2>&1; then
		if bpftool btf dump file /sys/kernel/btf/nf_flow_table format raw 2>/dev/null | grep -q bpf_xdp_flow_lookup; then
			ok "bpf_xdp_flow_lookup kfunc IS present"
		else
			bad "bpf_xdp_flow_lookup kfunc NOT found in nf_flow_table BTF"
		fi
	else
		skip "bpftool absent — cannot dump BTF"
	fi
else
	bad "no BTF for nf_flow_table (module not loaded, or BTF_MODULES off)"
fi

hdr "3. $WANIF exists and advertises the new feature set"
if $IP link show "$WANIF" >/dev/null 2>&1; then
	ok "$WANIF exists"
	$IP -d link show "$WANIF" | sed -n '1,3p' | sed 's/^/          /'
	if $IP -d link show "$WANIF" 2>/dev/null | grep -qi "redirect"; then
		ok "xdp-features advertises redirect"
	else
		skip "this iproute2 does not print xdp-features (not a failure)"
	fi
else
	bad "$WANIF not present — is the modem up? set WANIF=... and re-run"
	cleanup; exit 1
fi

# --- GRO aggregation measurement -------------------------------------------
gro_measure() {
	_s=${1:-12}
	_p0=$(cat /sys/class/net/$WANIF/statistics/rx_packets)
	_i0=$(awk '/^Ip:/{c++; if(c==2) print $3}' /proc/net/snmp)
	_j0=$(awk '/^Ip6InReceives/{print $2}' /proc/net/snmp6 2>/dev/null || echo 0)
	sleep "$_s"
	_p1=$(cat /sys/class/net/$WANIF/statistics/rx_packets)
	_i1=$(awk '/^Ip:/{c++; if(c==2) print $3}' /proc/net/snmp)
	_j1=$(awk '/^Ip6InReceives/{print $2}' /proc/net/snmp6 2>/dev/null || echo 0)
	_dp=$((_p1-_p0)); _ds=$(( (_i1-_i0) + (_j1-_j0) ))
	if [ "$_ds" -gt 0 ] && [ "$_dp" -gt 0 ]; then
		awk "BEGIN{printf \"%d %d %.2f\", $_dp, $_ds, $_dp/$_ds}"
	else
		echo "$_dp $_ds 0"
	fi
}

hdr "4. GRO baseline (no program attached)"
if [ "$WITH_TRAFFIC" = 1 ]; then
	start_traffic
else
	info "no load generator (pass --traffic to start one). Drive WAN traffic now, e.g."
	info "  wget -qO /dev/null https://speed.cloudflare.com/__down?bytes=1000000000 &"
fi
info "measuring for 12s ..."
set -- $(gro_measure 12)
BASE_RATIO=$3
info "$WANIF rx_packets=$1   IP InReceives=$2   aggregation=${3}x"
if [ "$1" -lt 500 ]; then
	skip "only $1 packets seen — too little traffic for a meaningful ratio"
	BASE_RATIO=0
elif awk "BEGIN{exit !($3 > 1.2)}"; then
	ok "gro_cells is aggregating (${3}x) — 991 is doing its job"
else
	info "aggregation ${3}x — low, but that is traffic-shape dependent, not a failure by itself"
fi

hdr "5. attach XDP in DRV mode — the 992 ndo_bpf test"
if $IP link set dev "$WANIF" xdp obj $D/xdp_pass.o sec xdp 2>$D/err; then
	MODE=$($IP -d link show "$WANIF" | grep -oE 'xdpgeneric|xdpdrv|xdp' | head -1)
	if [ "$MODE" = "xdpgeneric" ]; then
		bad "attached in GENERIC mode — ndo_bpf is not being used"
	else
		ok "attached in DRIVER mode ('$MODE') — 992's ndo_bpf captured it"
	fi
	$IP -d link show "$WANIF" | grep -o 'prog/xdp id [0-9]* name [a-z_]*' | sed 's/^/          /'
	ATTACHED=1
else
	bad "attach failed: $(head -2 $D/err | tr '\n' ' ')"
fi

hdr "6. THE decisive test: GRO must survive the attach"
if [ "$BASE_RATIO" = "0" ]; then
	skip "no usable baseline from step 4 — rerun with sustained WAN traffic"
else
	info "keep the traffic running; measuring again for 12s ..."
	set -- $(gro_measure 12)
	info "with XDP attached: rx_packets=$1  InReceives=$2  aggregation=${3}x   (baseline ${BASE_RATIO}x)"
	if awk "BEGIN{exit !($3 < 1.15)}"; then
		bad "aggregation collapsed to ${3}x — the program landed on dev->xdp_prog (generic), GRO is off"
	elif awk "BEGIN{exit !($3 > $BASE_RATIO * 0.6)}"; then
		ok "GRO survived the attach (${3}x vs ${BASE_RATIO}x baseline) — Method A working as designed"
	else
		bad "aggregation dropped a lot (${3}x vs ${BASE_RATIO}x) — investigate"
	fi
fi

hdr "7. rx_errors must not climb while a program is attached"
if [ -z "$ATTACHED" ]; then skip "nothing attached in step 5"; else
E0=$(cat /sys/class/net/$WANIF/statistics/rx_errors)
sleep 5
E1=$(cat /sys/class/net/$WANIF/statistics/rx_errors)
[ "$E1" -eq "$E0" ] && ok "rx_errors steady at $E0" || bad "rx_errors climbed $E0 -> $E1 (XDP_ABORTED / invalid verdicts?)"
fi

hdr "8. detach"
if [ -z "$ATTACHED" ]; then skip "nothing to detach"; else
$IP link set dev "$WANIF" xdp off 2>/dev/null
$IP -d link show "$WANIF" | grep -q "prog/xdp" && bad "program still attached after detach" || ok "detached cleanly"
fi

if [ "$WITH_DROP" = 1 ]; then
hdr "9. XDP_DROP  [5s WAN blackout — LAN/SSH unaffected]"
	P0=$(cat /sys/class/net/$WANIF/statistics/rx_packets)
	if $IP link set dev "$WANIF" xdp obj $D/xdp_drop.o sec xdp 2>$D/err; then
		sleep 5
		P1=$(cat /sys/class/net/$WANIF/statistics/rx_packets)
		$IP link set dev "$WANIF" xdp off
		D0=$((P1-P0))
		info "rx_packets moved by $D0 while XDP_DROP was attached"
		info "(the driver counts rx_packets AFTER the hook, so a working DROP keeps this near 0)"
		[ "$D0" -lt 50 ] && ok "XDP_DROP is dropping" || bad "packets still counted — DROP not taking effect"
	else
		bad "could not attach drop program: $(head -1 $D/err)"
	fi
else
	skip "XDP_DROP test (pass --with-drop to run it; 5s WAN blackout)"
fi

if [ "$WITH_TC" = 1 ]; then
hdr "10. tc-BPF on a raw-IP device: L3/L4 parse"
	if ! [ -n "$TC" ]; then
		skip "tc absent"
	else
		$TC qdisc show dev "$WANIF" | grep -q clsact || { $TC qdisc add dev "$WANIF" clsact && MADE_CLSACT=1; }
		if $TC filter add dev "$WANIF" ingress bpf da obj $D/tc_rawip.o sec classifier/rawip 2>$D/err; then
			ok "raw-IP tc-BPF program loaded and attached on ingress"
			mount -t tracefs nodev /sys/kernel/tracing 2>/dev/null
			if [ -r /sys/kernel/tracing/trace_pipe ]; then
				: > /sys/kernel/tracing/trace 2>/dev/null
				timeout 6 cat /sys/kernel/tracing/trace_pipe > $D/tp.out 2>/dev/null &
				sleep 5; kill %1 2>/dev/null
				if grep -q "RAWIP-OK v4\|RAWIP-OK v6" $D/tp.out 2>/dev/null; then
					ok "program parsed L3/L4 correctly on the raw-IP link:"
					grep "RAWIP-OK" $D/tp.out | head -3 | sed 's/^/          /'
				else
					skip "no trace output (needs live WAN traffic during the 5s window)"
				fi
			else
				skip "tracefs unavailable — cannot read bpf_printk output"
			fi
			$TC filter del dev "$WANIF" ingress 2>/dev/null
		else
			bad "tc-BPF load failed: $(head -3 $D/err | tr '\n' ' ')"
		fi
		[ -n "$MADE_CLSACT" ] && $TC qdisc del dev "$WANIF" clsact 2>/dev/null
	fi
else
	skip "tc-BPF test (pass --with-tc to run it)"
fi

hdr "11. AF_XDP — the case that used to oops"
if command -v xdp-loader >/dev/null 2>&1; then
	info "xdp-loader status:"
	xdp-loader status "$WANIF" 2>&1 | sed 's/^/          /'
	info "to test the old crash path:  xdp-loader load -m native $WANIF <af_xdp_prog.o>"
	info "then confirm nothing landed in /sys/fs/pstore/"
else
	skip "xdp-loader not installed"
fi
PST=$(ls -1 /sys/fs/pstore/ 2>/dev/null | wc -l)
[ "$PST" -eq 0 ] && ok "/sys/fs/pstore/ empty — no crash recorded" || bad "$PST entries in /sys/fs/pstore/ — inspect them"

hdr "12. telegraf footprint (task #86)"
if [ -e /usr/bin/telegraf ]; then
	SZ=$(stat -c%s /usr/bin/telegraf 2>/dev/null || echo 0)
	info "/usr/bin/telegraf: $((SZ/1048576)) MB uncompressed"
	if /etc/init.d/telegraf enabled 2>/dev/null; then
		bad "telegraf is ENABLED at boot"
	else
		ok "telegraf disabled at boot (97-telegraf-guard worked)"
	fi
	if pgrep telegraf >/dev/null 2>&1; then bad "telegraf is RUNNING"; else ok "telegraf not running"; fi
else
	ok "telegraf not installed"
fi
info "storage / memory:"
df -h / /overlay 2>/dev/null | sed 's/^/          /'
free -m 2>/dev/null | sed 's/^/          /'

stop_traffic

hdr "summary"
printf '  PASS=%d  FAIL=%d  skipped=%d\n' "$PASS" "$FAIL" "$SKIP"
cleanup
[ "$FAIL" -eq 0 ] || exit 1
